### ISSUE TITLE
Connecting with IOS device - response 400

### ISSUE THREAD

**Issue by chasgames** [LINKIWI/orion-docker#2] opened 2018-02-02 15:59 UTC
Hello,

Really awesome docker setup, and was easy to get it up and running, i can access my URL and the ORION map comes up just fine.

I'm having trouble connecting my Owntracks on my iPhone, I tired Private, then realized it must be HTTP method, so i put my http://url.com/api/publish in as the host, but it says http response 400.

If i nativigate to my url/api/publish it says "Method Not Allowed
The method is not allowed for the requested URL." 

Not sure of the settings to put in the iPhone or if i'm doing something incorrectly.

**Comment by LINKIWI** [comment] 2018-02-02 17:40
> but it says http response 400.

This is most likely due to orion-server#2. This is fixed as of orion-server@8a5f5025869865c3050ec1cd3febaaf6c3f7cc5f; what SHA are you currently running?

> If i nativigate to my url/api/publish it says "Method Not Allowed
> The method is not allowed for the requested URL."

This is because the `/api/publish` endpoint only responds to HTTP POST requests, while your browser can only issue an HTTP GET.

**Comment by chasgames** [comment] 2018-02-02 22:12
Thanks for the explanation,

My docker-compose SHA says 9c1430d6cd77e9ac16667d5b4c3e4a09f49ff5b7 for server and f83c614aa5c2e4b31233c8401304f750833f366d for web.

Should i re-build or change the SHA ?

**Comment by LINKIWI** [comment] 2018-02-02 23:37
My official recommendation is to deploy LINKIWI/orion-server directly without going through Docker. The Docker image scripts are complex and fragile.

However, you can try bumping the server SHA to the latest master (or just change it to "master" to grab whatever is on master) to see if that works with the current scripts. You shouldn't need to change the web SHA.

**Comment by LINKIWI** [comment] 2018-02-27 16:16
Closing due to inactivity

**Closed by LINKIWI** 2018-02-27 16:16 UTC

**Comment by taalas** [comment] 2018-07-18 16:17
Sorry to chime in on this, but see the same behaviour when using the orion-server master directly from github (without using docker). My iOS OwnTrack app reports error 400 when accessing the endpoint.

**Comment by LINKIWI** [comment] 2018-07-19 22:41
@taalas Happy to accept a patch if you are able to identify the problem and fix it. I don't have an iPhone so I have no reasonable way of investigating myself.

**Comment by gorfreed** [comment] 2020-12-15 19:31
Confirmed. This is not working for Owntracks on iOS devices unfortunately.
